@startuml statemachine

[*] -> idle
idle --> wifi_connecting 
wifi_connecting --> wifi_connected  : WIFI_EVENT: GOT_LOCAL_IP
wifi_connected --> wifi_disconnected : WIFI_EVENT: DISCONNECTED

wifi_disconnected --> wifi_connected: WIF_EVENT: GOT_LOCAL_IP


wifi_connected --> mqtt_connected: MQTT_EVENT: on_connected
mqtt_connected --> mqtt_disconnected : MQTT_EVENT: on_disconnected
mqtt_disconnected --> mqtt_connecting
mqtt_connecting --> mqtt_connected 

@endum;